<a href="https://colab.research.google.com/github/rlaalswn222/sesac_multimodal/blob/main/sesac05_python05_numpy02_241030.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

arr = [0][0]
print(arr)

0


In [7]:
arr = np.arange(12)
arr.size

12

In [9]:
arr.reshape #형태 변경

<function ndarray.reshape>

In [10]:
arr = np.arange(20).reshape(-1, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# transpose
.T와 transpose 방식 두가지로 진행되는데
두개의 축에 차이가 있긴하지만 중요하지 않음

In [12]:
arr.transpose() #행렬의 행과 열을 바꿔줌

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [13]:
arr.T # =Transpose

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

0~20까지의 숫자를 배열을 만든 다음에 arr1 에는 짝수, arr2에는 홀수

In [14]:
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [15]:
arr1 = np.arange(2, 21, 2)
arr2 = np.arange(1, 21, 2)

print(arr1)
print(arr2)

[ 2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]


In [16]:
arr = np.arange(30).reshape(2, 3, 5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [19]:
arr.reshape(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
arr.reshape(6, 5).T

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

#1차원

In [24]:
arr1d = np.arange(8)

In [25]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
arr1d[1]

1

In [27]:
arr1d[-1]

7

In [28]:
arr1d[:4]

array([0, 1, 2, 3])

In [29]:
arr1d[2:5]

array([2, 3, 4])

In [30]:
arr2d = np.arange(20).reshape(4, -1)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
arr2d[:3][:2]
#재귀적으로 슬라이싱 함
#재귀적 -> 행으로 인식 / 행렬로 인식하려면 , 로 접근

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
arr2d[:3, :2] #이렇게 해야 행렬로 인식함

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [34]:
arr3 = np.array([10, 20, 30, 40, 50, 60], int)
arr3

array([10, 20, 30, 40, 50, 60])

In [35]:
arr3%3 == 0 #bool형

array([False, False,  True, False, False,  True])

In [36]:
arr3[arr3%3==0] #값 변환해서 안에 조건을 만족하는 원소만 출력

array([30, 60])

In [37]:
arr4 = np.arange(10,20)

In [38]:
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
arr2d = np.arange(20).reshape(4, 5)

In [40]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
arr2d[[0,2]] #행으로 접근

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [44]:
arr2d[[0,1],[4]] #행0,1의 열4를 출력

array([4, 9])

In [45]:
arr2d[[0,1],[4,3]] #행 0,열 4 -> 4, 행1, 열3-> 8 출력

array([4, 8])

In [52]:
arr5 = np.arange(4).reshape(-1, 2)
arr5

array([[0, 1],
       [2, 3]])

In [49]:
arr5.sum(axis = 0) #열

array([2, 4])

In [50]:
arr5.sum(axis = 1) #행

array([1, 5])

In [53]:
arr5.mean()

1.5

In [54]:
arr5.mean(axis = 0) #열

array([1., 2.])

In [56]:
arr5.mean(axis = 1) #행

array([0.5, 2.5])

# Where

x if 조건 else y의 벡터화 버전

np.where(조건, x, y)

In [57]:
xarr = np.array([100, 200, 300, 400])
yarr = np.array([1, 2, 3, 4])
cond = np.array([True, False, True, False])

In [58]:
result = np.where(cond, xarr, yarr) #조건문이 맞으면 xarr, 틀리면 yarr
result

array([100,   2, 300,   4])

x와 y자리에 들어가는 인자가 배열이 아니여도 가능

In [59]:
xarr =  np.array([100, 200, 300, 400])
yarr = np.array([1, 2, 3, 4])
cond = np.array([True, False, True, False])

np.where(xarr>200, max(xarr), 0)


array([  0,   0, 400, 400])

In [60]:
np.where(xarr%3 == 0, 1, 0)

array([0, 0, 1, 0])

#arr.sort()
주어진 축에 따라 정렬

arr자체를 정렬

In [64]:
np.random.seed(42)
arr = np.random.randint(1, 100, size = 10)
arr

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [65]:
arr.sort()
arr

array([15, 21, 52, 61, 72, 75, 75, 83, 87, 93])

In [66]:
-np.sort(-arr) #내림차순 약간 귀찮

array([93, 87, 83, 75, 75, 72, 61, 52, 21, 15])