<a href="https://colab.research.google.com/github/rlaalswn222/sesac_multimodal/blob/main/sesac04_python0401_numpy01_241029.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

print(np.__version__)

1.26.4


In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr+arr)
print(arr/arr) #float

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
A = [1, 2, 3, 4]

a = np.array(A)
s = a[:2] #깊은 복사 값만 복사해옴
ass = a[::]

print('A의 출력입니다: %a' %a) #np.array를 사용하면 앞에 array([])
print('a의 출력입니다: %s' %s) #s = a[:2] 사용하면 안의 원소값만 복사
print('ass의 출력입니다: %s' %ass)

A의 출력입니다: array([1, 2, 3, 4])
a의 출력입니다: [1 2]
ass의 출력입니다: [1 2 3 4]


In [4]:
ss = a[:2].copy() #두 요소를 깊은 복사로 복사하여 ss에 저장합니다. 따라서 ss를 수정해도 a에 영향을 미치지 않습니다.
print(ss.size)
ss[0] = 99
print(a)
print(s)
print(ss)

2
[1 2 3 4]
[1 2]
[99  2]


# 브로드캐스팅

다른 모양의 배열 간의 산술 연산을 수행할 수 있도록 해주는 numpy기능

브로드캐스팅하기 위해선 연산을 수행하는 축을 제외한 나머지 축의 shape이 일치하거나 둘 중 하나의 길이가 1이여야함

다른 배열들 간의 연산이 어떤 조건을 만족했을때 가능해지도록 배열을 자동적으로 변환하는것

In [5]:
list_1 = [1,2,3]
#list_1 +3 오류남 container 자체에 +3은 안됨

In [6]:
arr + 3 #array는 됨 이게 numpy의 특징

array([[4, 5, 6],
       [7, 8, 9]])

In [7]:
10 - arr

array([[9, 8, 7],
       [6, 5, 4]])

In [8]:
arr1 = np.array([1, 2, 3])
arr + arr1

array([[2, 4, 6],
       [5, 7, 9]])

In [9]:
arr.shape

(2, 3)

In [10]:
arr1.shape #벡터는 열을 중시하기 때문에

(3,)

In [11]:
arr2 = np.array([1, 2])
arr+arr2 #행 열이 맞지않음
#ValueError: operands could not be broadcast together with shapes (2,3) (2,)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [12]:
a = np.array(range(20))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
b = np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
 a = np.array([1, 2, 3])
 b = np.array([4, 5, 6])
 np.hstack([a, b]) #수평 스택: 후입선출

array([1, 2, 3, 4, 5, 6])

In [15]:
np.concatenate((a, b), axis = 0) #axis = 0은 행으로 붙이라는거 (pandas에서는 열로 붙이라는거)

array([1, 2, 3, 4, 5, 6])

In [16]:
np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.concatenate((a, b), axis = 1) #axis = 1에서 AxisError가 남
#AxisError: axis 1 is out of bounds for array of dimension 1

AxisError: axis 1 is out of bounds for array of dimension 1

In [18]:
c = np.array([[0, 1, 2], [3, 4, 5]])
d = np.array([[6, 7, 8],[9, 10, 11]])

np.concatenate((c, d), axis =0)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.concatenate((c, d), axis =1)
#axis=1은 2D에서는 잘 일어남

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [20]:
np.column_stack([a, b])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
c = np.array([[0, 1, 2], [3, 4, 5]])
d = np.array([[6, 7, 8],[9, 10, 11]])

np.concatenate((c.T, d.T), axis =1) #.T 전치

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

#Random module

random으 난수를 발생시키는 모듈

seed: 난수 생성 초기값 부여

In [22]:
from random import randint

count = int(input('로또 번호를 몇개 생성할까요?> '))

for i in range(count):
  a = np.random.randint(1, 46, size=6)
  a.sort() #오름차순
  print(i+1, '. 로또번호: ', a)

로또 번호를 몇개 생성할까요?> 7
1 . 로또번호:  [ 2  4 24 31 33 40]
2 . 로또번호:  [ 2  8 10 25 27 45]
3 . 로또번호:  [ 1  4 15 24 29 41]
4 . 로또번호:  [ 1  8  9 22 41 45]
5 . 로또번호:  [ 7 16 20 31 34 38]
6 . 로또번호:  [ 5  6  8 17 22 31]
7 . 로또번호:  [22 25 30 35 35 38]


In [23]:
import numpy as np
def make_lotto(count):
  for i in range(count):
    lotto_num = np.random.choice(range(1, 46), 6, replace = False)
    lotto_num.sort()
    print("{}.로또 번호: {}".format(i+1, lotto_num))
count = int(input('로또 번호를 몇개 생성할까요?: '))
make_lotto(count)

로또 번호를 몇개 생성할까요?: 7
1.로또 번호: [ 3  4  5 16 21 38]
2.로또 번호: [26 31 33 40 42 45]
3.로또 번호: [17 26 33 39 40 45]
4.로또 번호: [ 8 16 21 24 29 30]
5.로또 번호: [ 7 10 18 27 35 45]
6.로또 번호: [ 1  7 21 27 32 45]
7.로또 번호: [ 2  4 15 26 27 38]
